modLoader="javafml" #mandatory
loaderVersion="[36,)" #mandatory This is typically bumped every Minecraft version by Forge. See our download page for lists of versions.
license="All rights reserved"
[[mods]] #mandatory
modId="peeled" #mandatory
version="${file.jarVersion}" #mandatory
displayName="Peeled" #mandatory
credits="Mr. Esuoh for the idea and sound"
authors="Coda" #optional
description='''
Peeled adds a sound whenever a player slips on a banana peel from Neapolitan!'''
[[dependencies.peeled]] #optional
    modId="forge" #mandatory
    mandatory=true #mandatory
    versionRange="[36,)" #mandatory
    ordering="NONE"
    side="BOTH"
[[dependencies.peeled]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.16.5,1.17)"
    ordering="NONE"
    side="BOTH"
